### ISSUE TITLE
Individual packages

### ISSUE THREAD

**Issue by ccorcos** [girassolbit/meteor-kouto-swiss#1]
It would be great if these packages could be installed separately.

**Comment by fakenickels** [comment]
Hi @ccorcos, we're currently considering doing that

**Comment by fakenickels** [comment]
The thing is that @charlenopires when started the package meant it to be a bundle of all those tools

**Comment by ccorcos** [comment]
Sure, but it would be great if those tools were all added separately. Much like how the `react` package is just a bundle of `react-runtime`, `jsx` and `react-meteor-data`. This is nice cause it allows me to choose only what I want.

**Comment by charlenopires** [comment]
But you can to choose what tool to use. If you will use only kouto-swiss, the package can to be used for this, only importing this tool in your stylus code, for example:

@import 'kouto-swiss'

but, if you want to use kouto-swiss + jeet + nib, you use an diff import in your stylus code main:

@import 'kouto-swiss'
@import 'jeet'
@import 'rupture'
@import 'nib'

The package has been designed to use what you need, when you need, but you gave me an idea to implement an new feature in the next version. Wait and see. Trust me. Thank you for your feedback.

**Comment by ccorcos** [comment]
Alright, I'll hang tight!
